# config file

params:
    # input files from radiative transfer (rt)
    rt_paths: ['example_data/']
    rt_patterns: ['rt_*_vers03-era5-clwc_*.nc', 'rt_10393_vers01_*.nc']
    
    # 3 letter site description
    site: 'rao'
    
    # site long name
    site_location: 'Lindenberg, DE'
    
    # version
    retrieval_version: 'tb00'
    
    # general specifications
    predictand_min: 0.
    predictand_max: 0.03

    # predictor
    predictor: 'tb'
    predictor_min: 2.73
    predictor_max: 330.
    tb_noise: 0.1
    
    predictor_error: [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15]
    
    # surface layer measurement uncertainties, T, p, q
    surface_error: [0.15, 100., .5e-3]
    
    # retrieval specifications
    freq: [22.24, 23.04, 23.84, 25.44, 26.24, 27.84, 31.4]

    angle: [90]
        
    surf_mode: 'no_surface'
        
            
