# config file

params:
    # general specifications
    predictand_min: 190.
    predictand_max: 330.

    # predictor
    predictor: 'tb'
    predictor_min: 2.73
    predictor_max: 330.
    tb_noise: 0.1
    
    predictor_error: [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
    
    # surface layer measurement uncertainties, T, p, q
    surface_error: [0.15, 100., .5e-3]
    
    # retrieval specifications
    freq: [51.26, 52.28, 53.86, 54.94, 56.66, 57.30, 58.00]

    angle: [90]
        
    surf_mode: 'no_surface'
        
            
