# config file for tpb retrievals

params:
    # general specifications
    predictand_min: 190.
    predictand_max: 330.

    # predictor
    predictor: 'tb'
    predictor_min: 2.73
    predictor_max: 330.
    tb_noise: 0.15

    # regression type (currently only linear)
    regression_type: 'linear'

    # surface layer measurement uncertainties, T, p, q
    surface_error: [0.2] # , 100., .5e-3]
