# config file

params:
    # general specifications
    predictand_min: 2.73
    predictand_max: 330.

    # predictor
    predictor: 'tb'
    predictor_min: 2.73
    predictor_max: 330.
    tb_noise: 0.15

    # regression type (linear or quadratic)
    regression_type: 'quadratic'

    predictor_error: [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
    # predictor_error: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]

    # surface layer measurement uncertainties, T, p, q
    surface_error: [0.2, 100., .5e-3]

    # retrieval specifications

    freq: [22.24, 23.04, 23.84, 25.44, 26.24, 27.84, 31.4, 51.26, 52.28, 53.86, 54.94, 56.66, 57.30, 58.00]

    angle: [90. , 30. , 19.2, 14.4, 11.4,  8.4,  6.6,  5.4,  4.8,  4.2]
