# config file

params:
    # general specifications
    predictand_min: 0.
    predictand_max: 60.

    # predictor
    predictor: 'tb'
    predictor_min: 2.73
    predictor_max: 330.
    tb_noise: 0.15

    # regression type (linear or quadratic)
    regression_type: 'quadratic'

    predictor_error: [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15]
    # predictor_error: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]

    # surface layer measurement uncertainties, T, p, q
    surface_error: [0.2, 100., .5e-3]

    # retrieval specifications
    freq: [22.24, 23.04, 23.84, 25.44, 26.24, 27.84, 31.4]

    angle: [90]
