# config file

params:
    # input files from radiative transfer (rt)
    rt_paths: ['example_data/']
    rt_patterns: ['rt_*_vers03-era5-clwc_*.nc', 'rt_10393_vers01_*.nc']

    # 3 letter site description
    site: 'RAO'
    
    # site long name
    site_location: 'Lindenberg, Germany'

    # version
    retrieval_version: 'tb01'
    
